site_name: Libro online de IAAR
pages:
    - Inteligencia Artificial: index.md
    - Deep Learning: deeplearning.md
    - Sobre IAAR: about.md
    - Contacto: contact.md
theme: readthedocs
site_url: https://iaarbook.github.io/
site_description: 'Libro online de la comunidad de Inteligencia Artificial Argentina IAAR'
