site_name: Libro online de IAAR
pages:
    - Inteligencia Artificial: index.md
    - Deep Learning: deeplearning.md
    - Machine Learning: ML.md
    - Ciencia de datos: datascience.md
    - Big Data: bigdata.md
    - Procesamiento de lenguaje: NLP.md
    - Intro Python: python.md
    - Intro R: rlang.md
    - Sobre IAAR: about.md
    - Sobre el autor: autor.md
    - Recursos: recursos.md
    - Bibliografía: bibliografia.md
    - Glosario: glosario.md
    - Contacto: contact.md
theme: readthedocs
site_url: https://iaarbook.github.io/
site_description: 'Libro online de la comunidad de Inteligencia Artificial Argentina IAAR'
google_analytics: ['UA-29080434-5', 'iaarbook']
theme_dir: myTheme
